(jde-project-file-version "1.0")
(jde-set-variables
 '(jde-project-name "default")
 '(jde-db-read-app-args t)
 '(jde-global-classpath (quote ("./src" "./classes" "./antlr-3.1.1.jar" "./commons-lang-2.2.jar" "./commons-cli-1.0.jar" "./log4j-1.2.14.jar" "./OpenFortranParser.jar")))
 '(jde-run-working-directory "./")
 '(jde-db-classic-mode-vm t)
 '(jde-run-option-classpath "global")
 '(jde-compile-option-directory "./classes")
 '(jde-compile-option-classpath (quote ("./src" "./classes" "./antlr-3.1.1.jar" "./commons-lang-2.2.jar" "./commons-cli-1.0.jar" "./log4j-1.2.14.jar" "./OpenFortranParser.jar")))
 '(jde-compile-option-sourcepath (quote ("./src")))
 '(jde-sourcepath (quote ("./src")))
 '(jde-run-application-class "ee.olegus.cpr.FortranCPR")
 '(jde-compile-option-debug (quote ("selected" (t t nil)))))
